{
  "contest": 52,
  "handle": "TomFrench",
  "address": "0x60959ed8307ee2b0d04306f6b319aeee8864f1ee",
  "risk": "2",
  "title": "VaderPoolV2.rescue results in loss of funds rather than recoverability",
  "issueId": 251,
  "issueUrl": "https://github.com/code-423n4/2021-11-vader-findings/issues/251"
}